tmpDir: tmp
host: "localhost"
port: 8000

url: "localhost:8000"

serveFiles:
  "/public": public
serverRenderer:
  enabled: true
  cache: fs
  cacheLifetime: 3600
frontend:
  indexTpl: public/index.html
crawler:
  onRun: true
  concurrentRequests: 1